### ISSUE TITLE
Visual glitch in player

### ISSUE THREAD

**Issue by inoricat** [orestescm76/cassiopeia#12]
Pause bars are vertical instead of horizontal.
Also play icon is very small and the stop one is bigger.

Version is latest beta 1.6.0.69, Windows DPI at default (100%). It happens on all languages. Can't reproduce it in 1.6.0.37, it works as intended there.

![image](https://user-images.githubusercontent.com/5923109/108633041-5371e900-7472-11eb-9995-44850f582b36.png)
![image](https://user-images.githubusercontent.com/5923109/108633060-73a1a800-7472-11eb-8f60-26c8dce1dc60.png)

**Comment by orestescm76** [comment]
i think i know where is this coming from and it's WinForms fault, since the text is an unicode character

**Comment by orestescm76** [comment]
just changed it to wingdings, like the skip buttons. should be OK now.

**Comment by orestescm76** [comment]
![image](https://user-images.githubusercontent.com/21990645/108634261-1b21d900-7479-11eb-89f9-80a5173f8262.png)
