### ISSUE TITLE
Road to 1.6

### ISSUE THREAD

**Issue by orestescm76** [orestescm76/cassiopeia#5]
Things I want for 1.6
 * Configuration form - Translate all program configurations to that form.
 * Playlist system - Create a new playlist system from scratch. Local songs.
 * Player fixes - Better player, fix bugs.
 * Translations
 * Better usability - Make error messages. Make dialogs so that the user notices a change in the program.
1.6 is avaliable on desarrollo branch.

**Comment by orestescm76** [comment]
Update 21/02
- Configuration form. 30% yet, still need to work on that.
- Playlist system. 90% completed.
- Player fixes. Oh well. Have strange errors with OGG playback. Only with certain files.
- Translations. Catalan and Greek.
- Better usability. 50%?

**Comment by orestescm76** [comment]
Update 22/02
- Playlist system is completed.
- Ogg issue is library's fault.

**Comment by orestescm76** [comment]
Update 26/02

- Config form remaining, create a section for visuals and add the colors and fonts.
- Translations, still Greek remaining :/
- Refactor, but that's not prioritary.

**Comment by Delunado** [comment]
@orestescm76 Refactoring is always a priority >:(

**Comment by orestescm76** [comment]
> @orestescm76 Refactoring is always a priority >:(

Well, it is important but not for this release at least 🙄
